import type { R26FlowEdge, R26FlowNode, R26Project } from './types';

const commonNode = {
  round: 1,
  collaborators: ['项目经理'],
  approver: '项目经理',
  startedAt: '2026-07-01 09:00',
  remainingDays: null,
  overdueDays: 0,
  requirement: '按流程要求完成本工序，并提交可追溯的业务材料。',
  output: '工序结论与配套材料',
  requiredMaterials: ['过程记录'],
  uploadedMaterials: ['过程记录'],
  missingMaterials: [] as string[],
  recentEvents: [{ time: '今天 09:20', text: '项目经理更新了工序说明' }],
};

export const r26FlowNodes: R26FlowNode[] = [
  {
    ...commonNode,
    step: 1,
    code: 'PROJECT_INITIATION',
    name: '反映市场需求',
    x: 625,
    y: 80,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'COMPLETED',
    owner: '周文远',
    department: '营销公司',
    deadline: '已于 7月1日完成',
    taskId: 't001',
  },
  {
    ...commonNode,
    step: 2,
    code: 'DEVELOPMENT_REPORT',
    name: '新颜色开发报告',
    x: 625,
    y: 190,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'COMPLETED',
    owner: '林若凡',
    department: '涂装工艺部',
    deadline: '已于 7月2日完成',
    taskId: 't002',
  },
  {
    ...commonNode,
    step: 3,
    code: 'PAINT_DEVELOPMENT',
    name: '涂料开发',
    x: 625,
    y: 300,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'COMPLETED_LATE',
    owner: '林若凡',
    department: '涂装工艺部',
    deadline: '已完成 · 曾逾期 1 天',
    taskId: 't003',
  },
  {
    ...commonNode,
    step: 4,
    code: 'SAMPLE_COLOR_CONFIRMATION',
    name: '样板颜色确认',
    x: 625,
    y: 410,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'COMPLETED',
    owner: '郭诗涵',
    department: '质量管理部',
    deadline: '已于 7月8日完成',
    taskId: 't004',
  },
  {
    ...commonNode,
    step: 5,
    code: 'COLOR_NUMBERING',
    name: '新颜色取号',
    x: 945,
    y: 410,
    width: 190,
    height: 92,
    shape: 'branch',
    status: 'COMPLETED',
    owner: '周文远',
    department: '营销公司',
    deadline: '已于 7月9日完成',
    taskId: 't005',
  },
  {
    ...commonNode,
    step: 6,
    code: 'PAINT_PROCUREMENT',
    name: '涂料采购',
    x: 625,
    y: 540,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'IN_PROGRESS',
    owner: '张七巧',
    department: '采购部',
    deadline: '今天 17:00',
    taskId: 't006',
    remainingDays: 0,
    requirement: '确认涂料到货、核对批次，并完成采购到货记录。',
    output: '采购到货确认与批次记录',
    requiredMaterials: ['采购订单', '供应商送货单', '到货确认记录'],
    uploadedMaterials: ['采购订单', '供应商送货单'],
    missingMaterials: ['到货确认记录'],
    recentEvents: [
      { time: '今天 10:08', text: '张七巧上传了供应商送货单' },
      { time: '昨天 16:40', text: '项目经理提醒补充到货确认记录' },
    ],
  },
  {
    ...commonNode,
    step: 7,
    code: 'STANDARD_BOARD_PRODUCTION',
    name: '标准板制作、下发',
    x: 945,
    y: 540,
    width: 190,
    height: 92,
    shape: 'branch',
    status: 'NOT_STARTED',
    owner: '何承宇',
    department: '涂装工艺部',
    deadline: '等待涂料采购完成',
    taskId: 't007',
  },
  {
    ...commonNode,
    step: 8,
    code: 'BOARD_DETAIL_UPDATE',
    name: '色板明细更新',
    x: 1185,
    y: 540,
    width: 190,
    height: 92,
    shape: 'branch',
    status: 'NOT_STARTED',
    owner: '何承宇',
    department: '涂装工艺部',
    deadline: '等待标准板下发',
    taskId: null,
  },
  {
    ...commonNode,
    step: 9,
    code: 'PERFORMANCE_TEST',
    name: '涂料性能试验',
    x: 305,
    y: 540,
    width: 190,
    height: 92,
    shape: 'branch',
    status: 'OVERDUE',
    owner: '郭诗涵',
    department: '质量管理部',
    deadline: '逾期 2 天',
    taskId: 't009',
    overdueDays: 2,
    missingMaterials: ['耐候性试验结果'],
    uploadedMaterials: [],
  },
  {
    ...commonNode,
    step: 10,
    code: 'FIRST_UNIT_PRODUCTION_PLAN',
    name: '首台生产计划',
    x: 625,
    y: 670,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'PENDING',
    owner: '赵知行',
    department: '生产部',
    deadline: '7月26日',
    taskId: 't010',
  },
  {
    ...commonNode,
    step: 11,
    code: 'TRIAL_PRODUCTION',
    name: '样车试制',
    x: 625,
    y: 800,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'RETURNED',
    owner: '赵知行',
    department: '生产部',
    deadline: '第 2 轮 · 待重新开始',
    taskId: 't011',
    round: 2,
    recentEvents: [
      { time: '7月18日 15:40', text: '驾驶室评审退回，需要修正喷涂均匀性' },
      { time: '7月16日 11:20', text: '第 1 轮样车试制完成' },
    ],
  },
  {
    ...commonNode,
    step: 12,
    code: 'CAB_REVIEW',
    name: '样车驾驶室评审',
    x: 615,
    y: 940,
    width: 210,
    height: 130,
    shape: 'decision',
    status: 'PENDING_REVIEW',
    owner: '郭诗涵',
    department: '质量管理部',
    deadline: '第 2 轮 · 等待评审',
    taskId: 't012',
    round: 2,
    approver: '郭诗涵、项目经理',
    requirement: '核对驾驶室颜色一致性，选择通过或退回并保留轮次记录。',
    output: '评审结论、退回原因与返工要求',
    recentEvents: [
      { time: '7月18日 15:40', text: '第 1 轮退回：喷涂均匀性不符合要求' },
      { time: '7月18日 09:30', text: '第 1 轮评审开始' },
    ],
  },
  {
    ...commonNode,
    step: 13,
    code: 'DEVELOPMENT_ACCEPTANCE',
    name: '颜色开发收费',
    x: 305,
    y: 1040,
    width: 190,
    height: 92,
    shape: 'branch',
    status: 'NOT_STARTED',
    owner: '财务专员',
    department: '财务部',
    deadline: '评审通过后创建',
    taskId: null,
    requirement: '费用以系统参数为准，静态原型不展示固定金额。',
  },
  {
    ...commonNode,
    step: 14,
    code: 'COLOR_CONSISTENCY_REVIEW',
    name: '颜色一致性评审',
    x: 625,
    y: 1120,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'NOT_STARTED',
    owner: '郭诗涵',
    department: '质量管理部',
    deadline: '等待驾驶室评审通过',
    taskId: null,
  },
  {
    ...commonNode,
    step: 15,
    code: 'MASS_PRODUCTION_PLAN',
    name: '排产计划',
    x: 625,
    y: 1250,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'NOT_STARTED',
    owner: '赵知行',
    department: '生产部',
    deadline: '等待颜色一致性评审',
    taskId: null,
  },
  {
    ...commonNode,
    step: 16,
    code: 'MASS_PRODUCTION',
    name: '批量生产',
    x: 625,
    y: 1380,
    width: 190,
    height: 92,
    shape: 'rounded',
    status: 'NOT_STARTED',
    owner: '赵知行',
    department: '生产部',
    deadline: '等待排产计划',
    taskId: null,
  },
  {
    ...commonNode,
    step: 17,
    code: 'VISUAL_COLOR_DIFFERENCE_REVIEW',
    name: '整车色差一致性评审',
    shortName: '色差目视评审',
    x: 605,
    y: 1510,
    width: 230,
    height: 100,
    shape: 'monthly',
    status: 'MONTHLY_TRACKING',
    owner: '郭诗涵',
    department: '质量管理部',
    deadline: '3 / 12 · 下次 8月15日',
    taskId: 't017',
    requirement: '每月完成一次色差评审，保留当月实例和逾期月份。',
    output: '12 个月独立评审记录',
    recentEvents: [
      { time: '7月15日', text: '第 3 个月评审已完成' },
      { time: '6月30日', text: '4 月评审曾逾期，已补录结论' },
    ],
  },
  {
    ...commonNode,
    step: 18,
    code: 'PROJECT_CLOSED',
    name: '颜色退出',
    x: 625,
    y: 1640,
    width: 190,
    height: 84,
    shape: 'terminal',
    status: 'EXIT_PENDING',
    owner: '项目经理',
    department: '项目组',
    deadline: '等待人工决定',
    taskId: null,
    requirement: '系统建议仅提供参考，最终退出结论由授权人员人工决定。',
    output: '颜色退出决定与生效日期',
  },
];

export const r26FlowEdges: R26FlowEdge[] = [
  { id: '01-02', from: 1, to: 2, path: 'M720 172 L720 190', type: 'mainline' },
  { id: '02-03', from: 2, to: 3, path: 'M720 282 L720 300', type: 'mainline' },
  { id: '03-04', from: 3, to: 4, path: 'M720 392 L720 410', type: 'mainline' },
  { id: '04-05', from: 4, to: 5, path: 'M815 456 L945 456', type: 'nonBlocking' },
  { id: '04-06', from: 4, to: 6, path: 'M720 502 L720 540', type: 'mainline' },
  { id: '06-09', from: 6, to: 9, path: 'M625 586 L495 586', type: 'nonBlocking' },
  { id: '06-07', from: 6, to: 7, path: 'M815 586 L945 586', type: 'parallel' },
  { id: '07-08', from: 7, to: 8, path: 'M1135 586 L1185 586', type: 'parallel' },
  { id: '06-10', from: 6, to: 10, path: 'M720 632 L720 670', type: 'mainline' },
  { id: '10-11', from: 10, to: 11, path: 'M720 762 L720 800', type: 'mainline' },
  { id: '11-12', from: 11, to: 12, path: 'M720 892 L720 940', type: 'mainline' },
  {
    id: '12-11',
    from: 12,
    to: 11,
    path: 'M825 1005 L940 1005 L940 846 L815 846',
    type: 'return',
    label: 'N',
  },
  {
    id: '12-13',
    from: 12,
    to: 13,
    path: 'M615 1005 L560 1005 L560 1086 L495 1086',
    type: 'nonBlocking',
    label: 'Y',
  },
  {
    id: '12-14',
    from: 12,
    to: 14,
    path: 'M720 1070 L720 1120',
    type: 'mainline',
    label: 'Y',
  },
  { id: '14-15', from: 14, to: 15, path: 'M720 1212 L720 1250', type: 'mainline' },
  { id: '15-16', from: 15, to: 16, path: 'M720 1342 L720 1380', type: 'mainline' },
  { id: '16-17', from: 16, to: 17, path: 'M720 1472 L720 1510', type: 'mainline' },
  { id: '17-18', from: 17, to: 18, path: 'M720 1610 L720 1640', type: 'mainline' },
];

export const r26Projects: R26Project[] = [
  {
    id: 'demo-r26',
    name: '深海蓝',
    colorName: '深海蓝',
    colorHex: '#1f4e79',
    tone: 'risk',
    status: '高风险',
    currentStep: '第 06 步 · 涂料采购',
    owner: '张七巧',
    deadline: '今天 17:00',
    progress: '7 / 18',
    updatedAt: '今天 10:08',
    riskReason: '缺少到货确认记录，采购工序无法形成完整交付证据。',
    expectedResolution: '预计明天 12:00 前补齐',
  },
  {
    id: 'silver-r26',
    name: '星河银',
    colorName: '星河银',
    colorHex: '#a5adb8',
    tone: 'review',
    status: '等待评审',
    currentStep: '第 12 步 · 样车驾驶室评审',
    owner: '郭诗涵',
    deadline: '明天 15:00',
    progress: '11 / 18',
    updatedAt: '昨天 16:40',
    riskReason: '第 1 轮评审退回，当前正在等待第 2 轮结论。',
    expectedResolution: '评审通过后进入一致性评审',
  },
  {
    id: 'white-r26',
    name: '极光白',
    colorName: '极光白',
    colorHex: '#f0f1ed',
    tone: 'tracking',
    status: '月度跟踪',
    currentStep: '第 17 步 · 整车色差一致性评审',
    owner: '郭诗涵',
    deadline: '下次 8月15日',
    progress: '3 / 12',
    updatedAt: '7月15日',
    riskReason: '4 月评审曾逾期，当前月份已恢复正常。',
    expectedResolution: '继续按月完成剩余 9 次评审',
  },
];

export const r26StatusLabels = {
  NOT_STARTED: '未开始',
  PENDING: '待处理',
  IN_PROGRESS: '进行中',
  PENDING_REVIEW: '待评审',
  COMPLETED: '已完成',
  COMPLETED_LATE: '已完成 · 曾逾期',
  OVERDUE: '已逾期',
  RETURNED: '已退回',
  MONTHLY_TRACKING: '月度跟踪',
  EXIT_PENDING: '待退出决定',
} satisfies Record<R26FlowNode['status'], string>;
